server:
  port: 8080
spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/use
    username: sa
    password:
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      formatSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        formatSql: true
        id:
          newGeneratorMappings: true
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: false
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#    leaseRenewalIntervalInSeconds: 3
#    leaseExpirationDurationInSeconds: 5